module.exports = {
    API_URL: "https://discordapp.com/api",
    CDN_URL: "https://cdn.discordapp.com/",
    RESTPoints: {
        Gateway: "/gateway?v=6",
        Channel: (cid) => `/channels/${cid}`,
        Messages: (mid) => `/channels/${mid}/messages`,
        Message: (cid, mid) => `/channels/${cid}/messages/${mid}`,
        BulkDeleteMessages: (cid) => `/channels/${cid}/message/bulk_delete`,
        PermissionsOverwrite: (cid, oid) => `/channels/${cid}/permissions/${oid}`,
        Invites: (cid) => `/channels/${cid}/invites`,
        Invite: (iid) => `/invites/${iid}`,
        Typing: (cid) => `/channels/${cid}/typing`,
        Pins: (cid) => `/channels/${cid}/pins`,
        Pinned: (cid, mid) => `/channels/${cid}/pins/${mid}`,
        GroupDMMember: (cid, uid) => `/channels/${cid}/recipients/${uid}`,
        Guilds: () => `/guilds`,
        Guild: (gid) => `/guilds/${gid}`,
        GuildChannels: (gid) => `/guilds/${gid}/channels`,
        Members: (gid) => `/guilds/${gid}/members`,
        Member: (gid, uid) => `/guilds/${gid}/members/${uid}`,
        Bans: (gid) => `/guilds/${gid}/bans`,
        Ban: (gid, uid) => `/guilds/${gid}/bans/${uid}`,
        Roles: (gid) => `/guilds/${gid}/roles`,
        Role: (gid, rid) => `/guilds/${gid}/roles/${rid}`,
        Prune: (gid) => `/guilds/${gid}/prune`,
        Regions: (gid) => `/guilds/${gid}/regions`,
        Integrations: (gid) => `/guilds/${gid}/integrations`,
        Integration: (gid, iid) => `/guilds/${gid}/integrations/${iid}`,
        IntegrationSync: (gid, iid) => `/guilds/${gid}/integrations/${iid}/sync`,
        GuildEmbed: (gid) => `/guilds/${gid}/embed`,
        BotUser: () => `/users/@me`,
        User: (uid) => `/users/${uid}`,
        BotGuilds: () => `/users/@me/guilds`,
        BotGuild: (gid) => `/users/@me/guilds/${gid}`,
        BotDMs: () => `/users/@me/channels`,
        BotConnections: () => `/users/@me/connections`,
        VoiceRegions: () => `/voice/regions`
    }
}